# Generated by Django 6.1 on 2026-08-14 11:18

import apps.games.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=apps.games.models.generate_room_code, max_length=8, unique=True)),
                ('game_type', models.CharField(choices=[('rps', 'Restricted Rock Paper Scissors'), ('ecard', 'E-card')], max_length=8)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for opponent'), ('active', 'In progress'), ('finished', 'Finished')], default='waiting', max_length=8)),
                ('state', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=64)),
                ('seat', models.PositiveSmallIntegerField()),
                ('is_bot', models.BooleanField(default=False)),
                ('display_name', models.CharField(blank=True, max_length=40)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='games.room')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('room', 'seat'), name='unique_seat_per_room')],
            },
        ),
    ]
