# Generated by Django 6.1 on 2026-08-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
    ]
